# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('commentaire_speudo', models.CharField(max_length=50)),
                ('contenu', models.TextField()),
                ('commentaire_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Commentaire',
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate', models.BooleanField()),
                ('entreprise_nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('quartier', models.CharField(max_length=20)),
                ('entreprise_adresse', models.TextField(max_length=200, verbose_name='Adresse')),
                ('entreprise_telephone', models.IntegerField()),
                ('entreprise_email', models.EmailField(max_length=254)),
                ('entreprise_site_web', models.CharField(blank=True, max_length=50)),
                ('entreprise_service', models.TextField(max_length=200)),
                ('cordonnee_longtitude', models.FloatField(blank=True, null=True)),
                ('cordonnee_laltitude', models.FloatField(blank=True, null=True)),
                ('date_publication', models.DateField(auto_now=True)),
                ('pubication', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('entreprise_local', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('entreprise_activity', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.Entreprise')),
            ],
            options={
                'verbose_name': 'Galerie',
                'verbose_name_plural': 'Galeries',
            },
        ),
        migrations.CreateModel(
            name='Heure_travail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=50)),
                ('heure_ouverture', models.TimeField()),
                ('heure_fermeture', models.TimeField()),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.Entreprise')),
            ],
            options={
                'verbose_name': 'Heure de travail',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_region', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='Representant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_proprietaire', models.CharField(max_length=50, unique=True)),
                ('nom_proprietaire', models.CharField(max_length=20)),
                ('prenom_proprietaire', models.CharField(max_length=15)),
                ('numero_proprietaire', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Representant',
                'verbose_name_plural': 'Representants',
            },
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secteur_nom', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': "Secteur d'activite",
                'verbose_name_plural': 'Seteurs dactivites',
            },
        ),
        migrations.AddField(
            model_name='entreprise',
            name='entreprise_secteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.Secteur'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.Representant'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.Region'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page1.Entreprise'),
        ),
    ]
