# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heure_travail',
            name='jour',
            field=models.CharField(choices=[('lundi', 'lundi'), ('mardi', 'mardi'), ('mercredi', 'mercredi'), ('jeudi', 'jeudi'), ('vendredi', 'vendredi'), ('samedi', 'samedi'), ('dimanche', 'dimanche')], max_length=15),
        ),
    ]
