# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0002_auto_20170324_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='galerie',
            name='autre',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
